import test from 'node:test';import assert from 'node:assert/strict';import handler from '../netlify/functions/restaurant-manage.mjs';
const agent='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',manager='00000000-0000-4000-8000-000000000003',venue='10000000-0000-4000-8000-000000000001';
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='sb_secret_test';
const req=(action,extra={},signed=true)=>new Request('https://example.netlify.app/api/restaurant-manage',{method:'POST',headers:{'content-type':'application/json',...(signed?{authorization:'Bearer test-token'}:{})},body:JSON.stringify({action,venue_id:venue,...extra})});
function mock({actor=agent,role='worker',active=true,support=true,access=[],published=true,menu=[{}],conflict=false}={}){const writes=[];global.fetch=async(url,init={})=>{const path=new URL(url).pathname,query=new URL(url).search;
 if(path==='/auth/v1/user')return Response.json({id:actor});
 if(init.method==='POST'&&path==='/auth/v1/admin/users'){writes.push({path,body:JSON.parse(init.body)});return conflict?Response.json({message:'exists'},{status:422}):Response.json({id:manager});}
 if(init.method==='POST'||init.method==='PATCH'){writes.push({path,body:JSON.parse(init.body)});return Response.json([JSON.parse(init.body)]);}
 if(path.includes('/profiles'))return Response.json([{id:actor,role,active}]);
 if(path.includes('/restaurant_venues'))return Response.json([{id:venue,owner_id:agent,created_by:agent,agent_support:support,published,menu,suspended:false}]);
 if(path.includes('/restaurant_manager_access'))return Response.json(access);throw Error('Unexpected path '+path+query);};return writes;}
test('unauthenticated manager provisioning never reaches Auth Admin',async()=>{const writes=mock();assert.equal((await handler(req('create-manager',{},false))).status,401);assert.equal(writes.length,0);});
test('agents cannot manage another agent venue or use admin controls',async()=>{let writes=mock({actor:other});assert.equal((await handler(req('create-manager'))).status,403);assert.equal(writes.length,0);writes=mock();assert.equal((await handler(req('suspend',{enabled:true}))).status,403);assert.equal(writes.length,0);});
test('disabled agents and agents after handover cannot provision managers',async()=>{for(const options of [{active:false},{support:false}]){const writes=mock(options);assert.equal((await handler(req('create-manager'))).status,403);assert.equal(writes.length,0);}});
test('manager accounts are restaurant only and password is never returned',async()=>{const writes=mock();const r=await handler(req('create-manager',{name:'Restaurant Manager',email:'manager@example.invalid',password:'a-long-demo-password'}));const body=await r.json();assert.equal(r.status,200);assert.equal(body.password,undefined);assert.equal(writes[0].body.app_metadata.account_type,'restaurant_manager');assert.equal(writes[1].body.active,false);assert.equal(writes[2].body.venue_id,venue);assert.equal(writes[2].body.user_id,manager);assert.equal(body.login_url,'https://example.netlify.app/restaurants/?manager=1');});
test('existing accounts are not reset by an agent',async()=>{const writes=mock({conflict:true});const r=await handler(req('create-manager',{name:'Manager',email:'existing@example.invalid',password:'a-long-demo-password'}));assert.equal(r.status,409);assert.equal(writes.length,1);});
test('handover requires a published menu and active manager',async()=>{for(const options of [{access:[]},{access:[{user_id:manager,active:true}],menu:[]},{access:[{user_id:manager,active:true}],published:false}]){const writes=mock(options);assert.equal((await handler(req('handover'))).status,400);assert.equal(writes.length,0);}const writes=mock({access:[{user_id:manager,active:true}]});assert.equal((await handler(req('handover'))).status,200);assert.deepEqual(writes[0].body,{agent_support:false});});
test('managers cannot create other manager accounts or pause a restaurant',async()=>{for(const action of ['create-manager','suspend']){const writes=mock({actor:manager,active:false,access:[{user_id:manager,active:true}]});assert.equal((await handler(req(action,{enabled:true}))).status,403);assert.equal(writes.length,0);}});
test('admin can pause restaurant and disable manager access',async()=>{let writes=mock({role:'admin'});assert.equal((await handler(req('suspend',{enabled:true}))).status,200);assert.deepEqual(writes[0].body,{suspended:true});writes=mock({role:'admin',access:[{user_id:manager,active:true}]});assert.equal((await handler(req('manager-active',{user_id:manager,active:false}))).status,200);assert.deepEqual(writes[0].body,{active:false});});
test('cross-origin manager creation is denied',async()=>{assert.equal((await handler(new Request('https://example.netlify.app/api/restaurant-manage',{method:'POST',headers:{origin:'https://other.example'},body:'{}'}))).status,403);});
