import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const ids=Array.from({length:6},(_,i)=>`00000000-0000-4000-8000-00000000000${i+1}`);
const [agent,other,admin,manager,otherManager,disabled]=ids;
const venues=Array.from({length:4},(_,i)=>`10000000-0000-4000-8000-00000000000${i+1}`);
test('restaurant manager isolation, immutable agent credit, admin commissions and storage ownership',async()=>{
 const db=new PGlite();
 try{
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema private;create schema storage;
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  create table auth.users(id uuid primary key,raw_app_meta_data jsonb default '{}');
  create table public.profiles(id uuid primary key,role text,name text,active boolean);
  create function private.is_admin(p_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=p_user and role='admin' and active)$$;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id bigint generated always as identity,bucket_id text,name text);
  alter table storage.objects enable row level security;grant insert on storage.objects to authenticated;grant usage on sequence storage.objects_id_seq to authenticated;
  grant usage on schema auth,private,public,storage to authenticated,anon,service_role;grant select on public.profiles to authenticated;
  alter table public.profiles enable row level security;create policy profile_read on public.profiles for select to authenticated using(id=auth.uid() or private.is_admin());
  insert into auth.users(id) values ${ids.map(id=>`('${id}')`).join(',')};
  insert into public.profiles values('${agent}','worker','Agent',true),('${other}','worker','Other',true),('${admin}','admin','Admin',true),('${manager}','worker','Manager',false),('${otherManager}','worker','Other Manager',false),('${disabled}','worker','Disabled',false);`);
  await db.exec(await readFile(new URL('../restaurant_setup.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/20261009063719_restaurant_manager_control.sql',import.meta.url),'utf8'));
  await db.exec(`insert into public.restaurant_venues(id,owner_id,created_by,name,slug,published,menu) values ${venues.map((id,i)=>`('${id}','${i===1?other:agent}','${i===1?other:agent}','Venue ${i}','venue-${i}',true,'[{"id":"dish","name":"Dish","price":12}]')`).join(',')};
  insert into public.restaurant_manager_access(venue_id,user_id,name,email) values('${venues[0]}','${manager}','Manager','mgr@example.invalid'),('${venues[1]}','${otherManager}','Other','other@example.invalid'),('${venues[2]}','${manager}','Manager','mgr@example.invalid'),('${venues[3]}','${manager}','Manager','mgr@example.invalid');
  update public.restaurant_venues set agent_support=false where id='${venues[2]}';update public.restaurant_venues set suspended=true where id='${venues[3]}';`);
  const as=async id=>db.exec(`reset role;set request.jwt.claim.sub='${id}';set role authenticated;`);
  const count=async table=>Number((await db.query(`select count(*) n from ${table}`)).rows[0].n);
  await as(admin);assert.equal(await count('public.restaurant_venues'),4);
  await db.exec(`insert into public.restaurant_commissions(venue_id,agent_id,amount,status) values('${venues[0]}','${agent}',300,'approved');`);
  await db.exec(`update public.restaurant_commissions set status='paid' where venue_id='${venues[0]}';`);
  assert.ok((await db.query('select paid_at from public.restaurant_commissions')).rows[0].paid_at);
  await assert.rejects(db.exec(`insert into public.restaurant_commissions(venue_id,agent_id,status) values('${venues[1]}','${other}','paid')`),/Approve/);
  await assert.rejects(db.exec(`insert into public.restaurant_commissions(venue_id,agent_id,status) values('${venues[3]}','${agent}','approved')`),/Publish a menu/);
  await assert.rejects(db.exec(`update public.restaurant_commissions set agent_id='${other}'`),/row-level security/);
  await as(agent);assert.equal(await count('public.restaurant_venues'),3);assert.equal(await count('public.restaurant_commissions'),1);
  assert.equal((await db.query(`update public.restaurant_venues set name='After handover' where id='${venues[2]}' returning id`)).rows.length,0);
  assert.equal((await db.query(`update public.restaurant_venues set name='Paused' where id='${venues[3]}' returning id`)).rows.length,0);
  await assert.rejects(db.exec(`update public.restaurant_venues set created_by='${other}' where id='${venues[0]}'`),/permission denied/);
  assert.equal((await db.query(`update public.restaurant_commissions set amount=999 returning venue_id`)).rows.length,0);
  await db.exec(`insert into public.restaurant_venues(name,slug,owner_id,created_by) values('New','new-venue','${other}','${other}')`);
  const credit=(await db.query("select created_by,owner_id from public.restaurant_venues where slug='new-venue'")).rows[0];assert.equal(credit.created_by,agent);assert.equal(credit.owner_id,agent);
  await as(manager);assert.equal(await count('public.restaurant_venues'),3);assert.equal(await count('public.restaurant_commissions'),0);
  assert.equal((await db.query(`update public.restaurant_venues set theme='garden',menu='[]' where id='${venues[0]}' returning theme`)).rows[0].theme,'garden');
  assert.equal((await db.query(`update public.restaurant_venues set theme='garden' where id='${venues[1]}' returning id`)).rows.length,0);
  await assert.rejects(db.exec("insert into public.restaurant_venues(name,slug) values('Unauthorized','unauthorized')"),/row-level security/);
  await assert.rejects(db.exec(`update public.restaurant_venues set agent_support=true where id='${venues[2]}'`),/permission denied/);
  await db.exec(`insert into storage.objects(bucket_id,name) values('restaurant-images','${venues[2]}/photo.webp')`);
  await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('restaurant-images','${venues[1]}/photo.webp')`),/row-level security/);
  await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('restaurant-images','${venues[3]}/photo.webp')`),/row-level security/);
  await assert.rejects(db.exec("insert into storage.objects(bucket_id,name) values('restaurant-images','invalid/photo.webp')"),/row-level security/);
  await as(disabled);assert.equal(await count('public.restaurant_venues'),0);
  await as(other);assert.equal(await count('public.restaurant_commissions'),0);
  await db.exec(`reset role;update auth.users set raw_app_meta_data='{"account_type":"restaurant_manager"}' where id='${manager}';update public.profiles set active=true where id='${manager}';`);
  assert.equal((await db.query(`select active from public.profiles where id='${manager}'`)).rows[0].active,false);
  await db.exec(`update public.restaurant_manager_access set active=false where user_id='${manager}';`);
  await as(manager);assert.equal(await count('public.restaurant_venues'),0);
  await db.exec('reset role;set role anon;');await assert.rejects(db.query('select * from public.restaurant_venues'),/permission denied/);await assert.rejects(db.query('select * from public.restaurant_commissions'),/permission denied/);
 }finally{await db.close();}
});
