import test from 'node:test';import assert from 'node:assert/strict';import handler from '../netlify/functions/restaurant-manage.mjs';
const agent='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',manager='00000000-0000-4000-8000-000000000003',venue='10000000-0000-4000-8000-000000000001';
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='sb_secret_test';
const req=(action,extra={},signed=true)=>new Request('https://example.netlify.app/api/restaurant-manage',{method:'POST',headers:{'content-type':'application/json',...(signed?{authorization:'Bearer test-token'}:{})},body:JSON.stringify({action,venue_id:venue,...extra})});
function mock({actor=agent,role='worker',active=true,support=true,access=[],published=true,menu=[{}],conflict=false,accountType='restaurant_manager',recoveryUser=manager,handedOver=false,existingAssignments=[],recoverable=false}={}){const writes=[];global.fetch=async(url,init={})=>{const path=new URL(url).pathname,query=new URL(url).search;
 if(path==='/auth/v1/user')return Response.json({id:actor});
 if(init.method==='POST'&&path==='/auth/v1/admin/users'){writes.push({path,body:JSON.parse(init.body)});return conflict?Response.json({message:'exists'},{status:422}):Response.json({id:manager});}
 if(path==='/auth/v1/admin/users/'+manager&&(!init.method||init.method==='GET'))return Response.json({id:manager,email:conflict?'existing@example.invalid':'manager@example.invalid',app_metadata:{account_type:accountType,...(recoverable?{setup_venue_id:venue,setup_actor_id:actor}:{})},user_metadata:{name:'Manager',locale:'en'}});
 if(path==='/auth/v1/admin/generate_link'){writes.push({path,body:JSON.parse(init.body)});return Response.json({user:{id:recoveryUser},hashed_token:'a'.repeat(64)});}
 if(init.method==='POST'||init.method==='PATCH'||init.method==='PUT'){writes.push({path,body:JSON.parse(init.body)});return Response.json([JSON.parse(init.body)]);}
 if(path.includes('/profiles')&&query.includes('email='))return Response.json([{id:manager}]);
 if(path.includes('/restaurant_manager_access')&&query.includes('user_id='))return Response.json(existingAssignments);
 if(path.includes('/profiles'))return Response.json([{id:actor,role,active}]);
 if(path.includes('/restaurant_venues'))return Response.json([{id:venue,owner_id:agent,created_by:agent,agent_support:support,handed_over_at:handedOver?'2026-10-09T01:00:00.000Z':null,published,menu,suspended:false}]);
 if(path.includes('/restaurant_manager_access'))return Response.json(access);throw Error('Unexpected path '+path+query);};return writes;}
test('unauthenticated manager provisioning never reaches Auth Admin',async()=>{const writes=mock();assert.equal((await handler(req('create-manager',{},false))).status,401);assert.equal(writes.length,0);});
test('agents cannot manage another agent venue or use admin controls',async()=>{let writes=mock({actor:other});assert.equal((await handler(req('create-manager'))).status,403);assert.equal(writes.length,0);writes=mock();assert.equal((await handler(req('suspend',{enabled:true}))).status,403);assert.equal(writes.length,0);});
test('disabled agents and agents after handover cannot provision managers',async()=>{for(const options of [{active:false},{support:false}]){const writes=mock(options);assert.equal((await handler(req('create-manager'))).status,403);assert.equal(writes.length,0);}});
test('manager accounts are restaurant only and password is never returned',async()=>{const writes=mock();const r=await handler(req('create-manager',{name:'Restaurant Manager',email:'manager@example.invalid',password:'a-long-demo-password'}));const body=await r.json();assert.equal(r.status,200);assert.equal(body.password,undefined);assert.equal(writes[0].body.app_metadata.account_type,'restaurant_manager');assert.equal(writes.length,2);assert.equal(writes[1].body.active,true);assert.equal(writes[1].body.venue_id,venue);assert.equal(writes[1].body.user_id,manager);assert.equal(writes[0].body.app_metadata.setup_venue_id,venue);assert.equal(body.login_url,'https://example.netlify.app/restaurants/?manager=1');});
test('existing accounts are not reset by an agent',async()=>{const writes=mock({conflict:true});const r=await handler(req('create-manager',{name:'Manager',email:'existing@example.invalid',password:'a-long-demo-password'}));assert.equal(r.status,409);assert.equal(writes.length,1);});
test('handover requires a published menu and active manager',async()=>{for(const options of [{access:[]},{access:[{user_id:manager,active:true}],menu:[]},{access:[{user_id:manager,active:true}],published:false}]){const writes=mock(options);assert.equal((await handler(req('handover'))).status,400);assert.equal(writes.length,0);}const writes=mock({access:[{user_id:manager,active:true}]});assert.equal((await handler(req('handover'))).status,200);assert.equal(writes[0].body.agent_support,false);assert.equal(writes[0].body.handed_over_by,agent);assert.ok(Date.parse(writes[0].body.handed_over_at));});
test('managers cannot create other manager accounts or pause a restaurant',async()=>{for(const action of ['create-manager','suspend']){const writes=mock({actor:manager,active:false,access:[{user_id:manager,active:true}]});assert.equal((await handler(req(action,{enabled:true}))).status,403);assert.equal(writes.length,0);}});
test('admin can pause restaurant and disable manager access',async()=>{let writes=mock({role:'admin'});assert.equal((await handler(req('suspend',{enabled:true}))).status,200);assert.deepEqual(writes[0].body,{suspended:true});writes=mock({role:'admin',access:[{user_id:manager,active:true}]});assert.equal((await handler(req('manager-active',{user_id:manager,active:false}))).status,200);assert.deepEqual(writes[0].body,{active:false});});
test('cross-origin manager creation is denied',async()=>{assert.equal((await handler(new Request('https://example.netlify.app/api/restaurant-manage',{method:'POST',headers:{origin:'https://other.example'},body:'{}'}))).status,403);});

test('manager reset and editing require an active administrator',async()=>{for(const action of ['reset-manager','edit-manager'])for(const options of [{},{actor:manager,active:false,access:[{user_id:manager,active:true}]},{role:'admin',active:false}]){const writes=mock(options);assert.equal((await handler(req(action,{user_id:manager,name:'Changed',email:'changed@example.invalid'}))).status,403);assert.equal(writes.length,0);}});
test('admin cannot edit or reset an unassigned account',async()=>{for(const action of ['reset-manager','edit-manager']){const writes=mock({role:'admin'});assert.equal((await handler(req(action,{user_id:manager}))).status,403);assert.equal(writes.length,0);}});
test('admin updates assigned manager login and display data without changing password or permissions',async()=>{const writes=mock({role:'admin',access:[{user_id:manager,active:true}]});const r=await handler(req('edit-manager',{user_id:manager,name:'Updated Manager',email:'NEW@example.invalid'}));assert.equal(r.status,200);assert.equal(writes.length,3);assert.deepEqual(writes[0].body,{email:'new@example.invalid',email_confirm:true,user_metadata:{name:'Updated Manager',locale:'en'}});assert.deepEqual(writes[1].body,{name:'Updated Manager',email:'new@example.invalid'});assert.equal(writes[0].body.password,undefined);assert.equal(writes[0].body.app_metadata,undefined);});
test('recovery link belongs to assigned manager and keeps token out of query parameters',async()=>{const writes=mock({role:'admin',access:[{user_id:manager,active:true}]});const r=await handler(req('reset-manager',{user_id:manager,email:'attacker@example.invalid',redirect_to:'https://attacker.example'}));assert.equal(r.status,200);const link=new URL((await r.json()).reset_url);assert.equal(link.origin,'https://example.netlify.app');assert.equal(link.pathname,'/restaurants/reset/');assert.equal(link.search,'');assert.equal(new URLSearchParams(link.hash.slice(1)).get('type'),'recovery');assert.deepEqual(writes[0].body,{type:'recovery',email:'manager@example.invalid'});});
test('disabled assignments, non-manager accounts and mismatched recovery targets cannot receive a reset link',async()=>{for(const options of [{access:[{user_id:manager,active:false}]},{access:[{user_id:manager,active:true}],accountType:'worker'},{access:[{user_id:manager,active:true}],recoveryUser:other}]){const writes=mock({role:'admin',...options});const r=await handler(req('reset-manager',{user_id:manager}));assert.ok(r.status>=400);assert.equal((await r.json()).reset_url,undefined);assert.ok(writes.length<=1);}});

test('admin recovers an orphan manager login without changing its password',async()=>{const writes=mock({role:'admin',conflict:true});const r=await handler(req('create-manager',{name:'Manager',email:'existing@example.invalid',recover:true}));assert.equal(r.status,200);assert.equal((await r.json()).reused,true);assert.equal(writes.length,1);assert.equal(writes[0].path,'/rest/v1/restaurant_manager_access');assert.equal(writes[0].body.password,undefined);});
test('agent can retry its own interrupted provisioning but cannot claim another login',async()=>{let writes=mock({conflict:true,recoverable:true});let r=await handler(req('create-manager',{name:'Manager',email:'existing@example.invalid',password:'a-long-demo-password'}));assert.equal(r.status,200);assert.equal((await r.json()).reused,true);assert.equal(writes.length,2);writes=mock({conflict:true,recoverable:true,existingAssignments:[{venue_id:'10000000-0000-4000-8000-000000000002'}]});r=await handler(req('create-manager',{name:'Manager',email:'existing@example.invalid',password:'a-long-demo-password'}));assert.equal(r.status,409);assert.equal(writes.length,1);});
test('repeat creation for the same assigned manager is idempotent',async()=>{const writes=mock({access:[{user_id:manager,active:true,email:'manager@example.invalid'}]});const r=await handler(req('create-manager',{name:'Manager',email:'manager@example.invalid'}));assert.equal(r.status,200);assert.equal((await r.json()).reused,true);assert.equal(writes.length,0);});
test('completed handovers block agent management even if support flag is stale and admin cannot restore it',async()=>{for(const role of ['worker','admin'])for(const action of ['support','assign-agent']){const writes=mock({role,handedOver:true,support:true});const r=await handler(req(action,{enabled:true,user_id:agent}));assert.equal(r.status,role==='admin'?409:403);assert.equal(writes.length,0);}});
